site_name: Steven-Vcnt
site_url: https://github.com/Steven-Vcnt/Steven-Vcnt/
repo_name: Steven-Vcnt/Steven-Vcnt
repo_url: https://github.com/Steven-Vcnt/Steven-Vcnt
edit_uri: edit/main/docs/

theme:
  name: material
  icon: 
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  



  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow
    #- toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - content.action.edit
    


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
